# ruff: noqa: E501
"""Build the AIUC-1 standard JSON from scraped data.

This script constructs the complete aiuc/aiuc-1-standard.json file
from data scraped from https://www.aiuc-1.com.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path


def build_aiuc_standard() -> dict:
    """Build the complete AIUC-1 standard data structure."""
    return {
        "standard": "AIUC-1",
        "version": "1.0",
        "url": "https://www.aiuc-1.com",
        "scraped_at": datetime.now(UTC).isoformat(),
        "domains": [
            _domain_a(),
            _domain_b(),
            _domain_c(),
            _domain_d(),
            _domain_e(),
            _domain_f(),
        ],
    }


def _ctrl(
    id: str,
    title: str,
    url: str,
    classification: str,
    type: str,
    frequency: str,
    description: str,
    applicable_capabilities: list[str],
    activities: list[dict],
    keywords: list[str],
    framework_references: dict,
) -> dict:
    return {
        "id": id,
        "title": title,
        "url": f"https://www.aiuc-1.com{url}",
        "classification": classification,
        "type": type,
        "frequency": frequency,
        "description": description,
        "applicable_capabilities": applicable_capabilities,
        "activities": activities,
        "keywords": keywords,
        "framework_references": framework_references,
    }


def _act(id: str, description: str, category: str = "Core", evidence_types: list[str] | None = None) -> dict:
    return {
        "id": id,
        "description": description,
        "category": category,
        "evidence_types": evidence_types or [],
    }


def _refs(
    eu_ai_act: list[str] | None = None,
    iso_42001: list[str] | None = None,
    nist_ai_rmf: list[str] | None = None,
    csa_aicm: list[str] | None = None,
    owasp_llm_top10: list[str] | None = None,
    owasp_aivss: list[str] | None = None,
    mitre_atlas: list[str] | None = None,
) -> dict:
    return {
        "eu_ai_act": eu_ai_act or [],
        "iso_42001": iso_42001 or [],
        "nist_ai_rmf": nist_ai_rmf or [],
        "csa_aicm": csa_aicm or [],
        "owasp_llm_top10": owasp_llm_top10 or [],
        "owasp_aivss": owasp_aivss or [],
        "mitre_atlas": mitre_atlas or [],
    }


# ── Domain A: Data & Privacy ────────────────────────────────────────────────


def _domain_a() -> dict:
    return {
        "id": "A",
        "name": "Data & Privacy",
        "url": "https://www.aiuc-1.com/data-and-privacy",
        "description": "Protect against data leakage, IP leakage, and training on user data without consent",
        "controls": [
            _ctrl("A001", "Establish input data policy", "/data-and-privacy/establish-data-use-policy", "Mandatory", "Preventative", "Every 12 months",
                   "Establish and communicate AI input data policies covering how customer data is used for model training, inference processing, data retention periods, and customer data rights.",
                   ["Universal"],
                   [_act("A001.1", "Define and communicate input data usage policies including how customer data is used for inference and model training, establishing data retention periods, and documenting customer data rights.", "Core", ["Terms of Service", "Privacy Policy", "Data Processing Agreement"]),
                    _act("A001.2", "Implement technical controls to enforce data retention and deletion policies through automating data deletion based on retention schedules.", "Core", ["Automated deletion implementation"]),
                    _act("A001.3", "Document processes for handling end-user data subject rights including opt-in/opt-out rights, access, portability, or deletion of input data.", "Supplemental", ["DPA", "GDPR appendix", "Privacy Policy"])],
                   ["Data Retention", "Model Training Data", "Opt-Out"],
                   _refs(eu_ai_act=["Article 11"], iso_42001=["A.7.2", "A.7.3"], nist_ai_rmf=["MEASURE 2.10"], csa_aicm=["DSP-11", "DSP-12", "DSP-13", "DSP-14", "DSP-15", "DSP-16", "DSP-09", "DSP-20", "DSP-23"])),
            _ctrl("A002", "Establish output data policy", "/data-and-privacy/define-output-rights", "Mandatory", "Preventative", "Every 12 months",
                   "Establish AI output ownership, usage, opt-out and deletion policies to customers and communicate these policies.",
                   ["Universal"],
                   [_act("A002.1", "Establishing output ownership and usage rights policies, specifying customer ownership of AI-generated outputs, defining permitted uses, documenting usage restrictions, and disclosing opt-out and deletion procedures.", "Core", ["Terms of Service"])],
                   ["Data Ownership", "Usage", "Deletion", "Consent", "Opt-Out"],
                   _refs(csa_aicm=["DSP-16", "DSP-08"])),
            _ctrl("A003", "Limit AI agent data collection", "/data-and-privacy/implement-contextual-data-safeguards", "Mandatory", "Preventative", "Every 12 months",
                   "Implement safeguards to limit AI agent data access to task-relevant information based on user roles and context.",
                   ["Universal"],
                   [_act("A003.1", "Configuring data collection limits to reduce data and privacy exposure, limiting data collection to task-relevant information based on context.", "Core", ["Code implementing data collection restrictions"]),
                    _act("A003.2", "Deploying monitoring mechanisms ensuring AI systems only perform necessary inference and logging deviations from defined operational scope.", "Supplemental", ["Alert/error handling code"]),
                    _act("A003.3", "Integrating with existing authorization systems to align agent access permissions with organizational policies.", "Supplemental", ["Authorization system code"])],
                   ["Data Collection", "Data Access", "Agent Permissions", "Access Permissions"],
                   _refs(nist_ai_rmf=["MAP 2.1"], owasp_llm_top10=["LLM06", "LLM08", "LLM10"], csa_aicm=["DSP-07", "AIS-11", "DSP-08", "DSP-22", "IAM-17", "IAM-19", "MDS-04"], owasp_aivss=["Agent Access Control Violation"])),
            _ctrl("A004", "Protect IP & trade secrets", "/data-and-privacy/protect-ip-trade-secrets", "Mandatory", "Preventative", "Every 12 months",
                   "Implement safeguards or technical controls to prevent AI systems from leaking company intellectual property or confidential information.",
                   ["Universal"],
                   [_act("A004.1", "Providing user guidance on protecting confidential information.", "Core", ["Policy document", "Training materials"]),
                    _act("A004.2", "Leveraging foundation model provider protections with zero data retention policies.", "Supplemental", ["Provider contracts"]),
                    _act("A004.3", "Implementing technical controls to detect proprietary information in outputs.", "Supplemental", ["IP detection code"]),
                    _act("A004.4", "Establishing output monitoring for high-risk IP scenarios.", "Supplemental", ["Audit trails", "Review workflows"])],
                   ["Intellectual Property", "Confidential Information", "Data Protections"],
                   _refs(eu_ai_act=["Article 72"], owasp_llm_top10=["LLM03", "LLM05", "LLM08"], csa_aicm=["DSP-01", "DSP-10", "DSP-02", "DSP-07", "DSP-08", "DSP-16", "UEM-08", "DSP-12"], mitre_atlas=["AML-M0020"], owasp_aivss=["Insecure Agent Critical Systems Interaction"])),
            _ctrl("A005", "Prevent cross-customer data exposure", "/data-and-privacy/prevent-cross-customer-data-exposure", "Mandatory", "Preventative", "Every 12 months",
                   "Implement safeguards to prevent cross-customer data exposure when combining customer data from multiple sources.",
                   ["Universal"],
                   [_act("A005.1", "Establishing explicit consent and disclosure for combined data usage.", "Core", ["Data Processing Agreement", "Terms of Service"]),
                    _act("A005.2", "Implementing customer data isolation controls with strict logical and physical separation.", "Core", ["Database schema screenshots"]),
                    _act("A005.3", "Implementing privacy-enhancing technologies to reduce competitive exposure.", "Supplemental", ["Tokenization", "Differential privacy"])],
                   ["Cross-Customer Data", "Model Training", "Data Rights"],
                   _refs(nist_ai_rmf=["MEASURE 2.10"], owasp_llm_top10=["LLM02", "LLM05", "LLM08"], csa_aicm=["I&S-06", "DSP-22"])),
            _ctrl("A006", "Prevent PII leakage", "/data-and-privacy/prevent-pii-leakage", "Mandatory", "Preventative", "Every 12 months",
                   "Establish safeguards to prevent personal data leakage through AI outputs and logs.",
                   ["Universal"],
                   [_act("A006.1", "Implementing safeguards to prevent personal data leakage through AI system outputs and logs, filtering prompts and outputs for personal identifiers.", "Core", ["PII filtering code"]),
                    _act("A006.2", "Requiring authentication and authorization for PII access with role-based access controls.", "Core", ["IAM configuration"]),
                    _act("A006.3", "Integrating with existing data loss prevention (DLP) systems to monitor and block outputs containing personal data.", "Supplemental", ["DLP integration code"])],
                   ["Personal Data Leakage"],
                   _refs(eu_ai_act=["Article 72"], nist_ai_rmf=["MEASURE 2.10"], owasp_llm_top10=["LLM02", "LLM05", "LLM08"], csa_aicm=["DSP-10", "DSP-17", "HRS-12", "DSP-13", "UEM-08", "DSP-12"], mitre_atlas=["AML-M0020"])),
            _ctrl("A007", "Prevent IP violations", "/data-and-privacy/prevent-ip-violations", "Mandatory", "Preventative", "Every 12 months",
                   "Implement safeguards and technical controls to prevent AI outputs from violating copyrights, trademarks, or other third-party intellectual property rights.",
                   ["External-facing"],
                   [_act("A007.1", "Documenting foundation model provider IP protections including indemnification clauses.", "Core", ["Foundation model provider contract"]),
                    _act("A007.2", "Establishing supplementary content filtering mechanisms for IP screening.", "Supplemental", ["IP filtering code"]),
                    _act("A007.3", "Implementing user guidance and guardrails to reduce IP risk.", "Supplemental", ["UI screenshots"])],
                   ["Intellectual Property", "Copyright Protection"],
                   _refs(nist_ai_rmf=["GOVERN 6.1", "MAP 4.1"], iso_42001=["A.7.5"], owasp_llm_top10=["LLM03", "LLM05"], csa_aicm=["AIS-09"], mitre_atlas=["AML-M0020"])),
        ],
    }


# ── Domain B: Security ───────────────────────────────────────────────────────


def _domain_b() -> dict:
    return {
        "id": "B",
        "name": "Security",
        "url": "https://www.aiuc-1.com/security",
        "description": "Protect AI systems against adversarial attacks, unauthorized access, and data exposure",
        "controls": [
            _ctrl("B001", "Third-party testing of adversarial robustness", "/security/test-adversarial-robustness", "Mandatory", "Preventative", "Every 3 months",
                   "Implement adversarial testing program to validate system resilience against adversarial inputs and prompt injection attempts.",
                   ["Universal"],
                   [_act("B001.1", "Third-party evaluation report demonstrating adversarial robustness testing including risk taxonomy, methodology, findings, and remediation timelines.", "Core", ["Third-party evaluation report"]),
                    _act("B001.2", "Penetration test reports incorporating AI-specific test cases, shared threat models, and testing calendars.", "Supplemental", ["Engineering Practice"])],
                   ["Adversarial Testing", "Red Teaming", "Prompt Injection", "Jailbreak"],
                   _refs(nist_ai_rmf=["GOVERN 4.3", "MEASURE 2.1", "MEASURE 2.6", "MEASURE 2.7"], owasp_llm_top10=["LLM01", "LLM04", "LLM05", "LLM08"], csa_aicm=["AIS-07", "AIS-08", "MDS-06", "MDS-07", "TVM-01", "TVM-03", "TVM-05", "TVM-06", "TVM-07", "TVM-08", "TVM-12", "TVM-13"], owasp_aivss=["Agent Cascading Failures", "Agent Goal and Instruction Manipulation"], mitre_atlas=["AML-M0003", "AML-M0004"])),
            _ctrl("B002", "Detect adversarial input", "/security/detect-adversarial-input", "Optional", "Detective", "Every 3 months",
                   "Implement monitoring capabilities to detect and respond to adversarial inputs and prompt injection attempts.",
                   ["Universal"],
                   [_act("B002.1", "Implementing monitoring for prompt injection patterns, jailbreak techniques, adversarial input attempts.", "Core", ["Monitoring system screenshots"]),
                    _act("B002.2", "Logging suspected adversarial attacks with relevant context and escalating based on severity.", "Core", ["Incident management system"]),
                    _act("B002.3", "Updating detection rules based on emerging adversarial techniques quarterly.", "Core", ["Quarterly review documentation"]),
                    _act("B002.4", "Implementing adversarial input detection prior to AI model processing.", "Supplemental", ["Pre-processing filtering logic"]),
                    _act("B002.5", "Integrating adversarial input detection into existing security operations tooling.", "Supplemental", ["SIEM platform screenshots"])],
                   ["Monitor", "Adversarial", "Jailbreak", "Prompt Injection"],
                   _refs(eu_ai_act=["Article 15", "Article 72"], nist_ai_rmf=["GOVERN 1.5", "MEASURE 2.4", "MEASURE 2.7", "MEASURE 3.1"], owasp_llm_top10=["LLM01", "LLM08", "LLM10"], csa_aicm=["AIS-08", "AIS-10", "LOG-14", "MDS-07", "TVM-01", "TVM-02", "TVM-04", "UEM-09"], owasp_aivss=["Agent Goal and Instruction Manipulation"], mitre_atlas=["AML-M0003", "AML-M0015", "AML-M0021", "AML-M0024"])),
            _ctrl("B003", "Manage public release of technical details", "/security/limit-technical-over-disclosure", "Optional", "Preventative", "Every 12 months",
                   "Implement controls to prevent over-disclosure of technical information about AI systems.",
                   ["Universal"],
                   [_act("B003.1", "Policy document defining limitations and approval requirements for publicly sharing AI system technical details.", "Core", ["Internal policies"]),
                    _act("B003.2", "Approval records for public AI communications.", "Supplemental", ["Internal processes"])],
                   ["Public Disclosure", "Open-Source", "External Threats"],
                   _refs(owasp_llm_top10=["LLM02", "LLM07"], csa_aicm=["AIS-09", "AIS-15"], mitre_atlas=["AML-M0000", "AML-M0001"])),
            _ctrl("B004", "Prevent AI endpoint scraping", "/security/prevent-ai-endpoint-scraping", "Mandatory", "Preventative", "Every 12 months",
                   "Implement safeguards to prevent probing or scraping of external AI endpoints.",
                   ["Universal"],
                   [_act("B004.1", "Implementing systems distinguishing between high-volume legitimate usage and adversarial behavior.", "Core", ["Anomaly detection system"]),
                    _act("B004.2", "Implementing rate limiting and query restrictions.", "Core", ["Rate limiting configuration"]),
                    _act("B004.3", "Conducting simulated external attack testing of AI endpoints.", "Core", ["Penetration test report"]),
                    _act("B004.4", "Tracking identified vulnerabilities and implementing protective measures.", "Core", ["Issue tracking system"])],
                   ["Scraping", "Probing", "Rate Limiting", "Query Quotas", "Zero Trust"],
                   _refs(eu_ai_act=["Article 15"], nist_ai_rmf=["MEASURE 2.7"], owasp_llm_top10=["LLM02", "LLM05", "LLM08", "LLM10"], csa_aicm=["AIS-10", "TVM-06", "UEM-01", "UEM-05", "UEM-09", "UEM-10", "UEM-11", "UEM-14"], owasp_aivss=["Agentic AI Tool Misuse"], mitre_atlas=["AML-M0003", "AML-M0004"])),
            _ctrl("B005", "Implement real-time input filtering", "/security/implement-real-time-input-filtering", "Optional", "Detective", "Every 12 months",
                   "Implement real-time input filtering using automated moderation tools.",
                   ["Text-generation", "Voice-generation", "Image-generation"],
                   [_act("B005.1", "Integration of automated moderation tools to filter inputs before reaching the foundation model.", "Core", ["Configuration screenshots"]),
                    _act("B005.2", "Documentation explaining moderation approach including tool selection rationale and threshold settings.", "Core", ["Internal documentation"]),
                    _act("B005.3", "User-facing communication when inputs are blocked.", "Core", ["UI screenshots"]),
                    _act("B005.4", "Logging system capturing flagged inputs with metadata tracking.", "Core", ["Logging system screenshots"]),
                    _act("B005.5", "Analysis of filter performance metrics with documented threshold adjustments.", "Core", ["Performance reports"])],
                   ["Prompt Injection", "Jailbreak", "Adversarial Input Protection"],
                   _refs(nist_ai_rmf=["MEASURE 2.7"], owasp_llm_top10=["LLM01", "LLM04", "LLM10"], csa_aicm=["AIS-08", "AIS-15", "LOG-14"], owasp_aivss=["Agent Goal and Instruction Manipulation"], mitre_atlas=["AML-M0015", "AML-M0021"])),
            _ctrl("B006", "Prevent unauthorized AI agent actions", "/security/enforce-contextual-access-controls", "Mandatory", "Preventative", "Every 12 months",
                   "Implement safeguards to prevent AI agents from performing actions beyond intended scope and authorized privileges.",
                   ["Automation"],
                   [_act("B006.1", "Restricting agent access to approved backend services and APIs, enforcing network segmentation or API gateway rules.", "Core", ["Agent backend access limits configuration"]),
                    _act("B006.2", "Deploying monitoring and alerting for agent actions that exceed security boundaries.", "Core", ["Monitoring configuration"])],
                   ["Access Permissions", "Agent Permissions"],
                   _refs(nist_ai_rmf=["MAP 2.1"], owasp_llm_top10=["LLM08", "LLM10"], csa_aicm=["AIS-11", "IAM-19", "DSP-07"], owasp_aivss=["Agent Access Control Violation", "Agent Orchestration and Multi-Agent Exploitation"])),
            _ctrl("B007", "Enforce user access privileges to AI systems", "/security/enforce-ai-access-privileges", "Mandatory", "Preventative", "Every 3 months",
                   "Establish and maintain user access controls and admin privileges for AI systems in line with policy.",
                   ["Universal"],
                   [_act("B007.1", "System-level access controls tailored to AI systems using role-based or attribute-based access.", "Core", ["IAM platform screenshots"]),
                    _act("B007.2", "Conducting access reviews and updates at least quarterly.", "Core", ["Quarterly access review documentation"])],
                   ["Access Controls", "Organizational Policy"],
                   _refs(owasp_llm_top10=["LLM02", "LLM06", "LLM10"], csa_aicm=["DSP-07", "DSP-08", "IAM-01", "IAM-02", "IAM-03", "IAM-04", "IAM-05", "IAM-06", "IAM-07", "IAM-08", "IAM-09", "IAM-10", "IAM-13", "IAM-14", "IAM-15", "IAM-16", "IAM-17", "IAM-18", "LOG-04", "LOG-09", "LOG-12"], mitre_atlas=["AML-M0005", "AML-M0019"])),
            _ctrl("B008", "Protect model deployment environment", "/security/protect-model-deployment-environment", "Mandatory", "Preventative", "Every 12 months",
                   "Implement security measures for AI model deployment environments including encryption, access controls and authorization.",
                   ["Universal"],
                   [_act("B008.1", "Restricting access to production AI models based on job function.", "Core", ["IAM configuration"]),
                    _act("B008.2", "Applying scoped API tokens, TLS for all endpoint traffic, schema validation.", "Core", ["API security configuration"]),
                    _act("B008.3", "Securing model hosting environments with minimal container images.", "Supplemental", ["Container configuration"]),
                    _act("B008.4", "Verifying model integrity before deployment using cryptographic checksums.", "Supplemental", ["Deployment pipeline"])],
                   ["Model Environment", "Encryption", "Access Controls"],
                   _refs(eu_ai_act=["Article 15"], owasp_llm_top10=["LLM07"], csa_aicm=["AIS-02", "AIS-06", "AIS-14", "DSP-07", "IAM-04", "IAM-14", "MDS-01", "MDS-02", "MDS-08", "MDS-09", "UEM-08"], owasp_aivss=["Agent Memory and Context Manipulation"], mitre_atlas=["AML-M0005", "AML-M0012", "AML-M0019"])),
            _ctrl("B009", "Limit output over-exposure", "/security/limit-output-over-exposure", "Mandatory", "Preventative", "Every 12 months",
                   "Implement output limitations and obfuscation techniques to safeguard against information leakage.",
                   ["Text-generation", "Voice-generation"],
                   [_act("B009.1", "Reducing or limiting the number of results shown in outputs to relevant only.", "Core", ["Output restriction code"]),
                    _act("B009.2", "Providing user-facing notices about output limitations.", "Supplemental", ["Product interface screenshots"]),
                    _act("B009.3", "Limiting the fidelity of model outputs with rounding, threshold bands, or obfuscation.", "Core", ["Fidelity limitation code"])],
                   ["Output Obfuscation", "Fidelity Reduction", "Information Leakage", "Response Filtering"],
                   _refs(nist_ai_rmf=["MEASURE 2.10"], owasp_llm_top10=["LLM02", "LLM05", "LLM08", "LLM09"], csa_aicm=["AIS-09"], mitre_atlas=["AML-M0002"])),
        ],
    }


# ── Domain C: Safety ─────────────────────────────────────────────────────────


def _domain_c() -> dict:
    return {
        "id": "C",
        "name": "Safety",
        "url": "https://www.aiuc-1.com/safety",
        "description": "Prevent harmful AI outputs and brand risk through testing, monitoring and safeguards",
        "controls": [
            _ctrl("C001", "Define AI risk taxonomy", "/safety/define-ai-risk-taxonomy", "Mandatory", "Preventative", "Every 3 months",
                   "Establish a risk taxonomy that categorizes risks within harmful, out-of-scope, and hallucinated outputs, tool calls, and other risks based on application-specific usage.",
                   ["Universal"],
                   [_act("C001.1", "Internal policy document or risk framework defining AI risk categories with severity levels and examples.", "Core", ["Risk taxonomy document"]),
                    _act("C001.2", "Quarterly reviews of risk taxonomy with review dates, participants, decisions, and version history.", "Core", ["Review documentation"])],
                   ["Risk Taxonomy", "Severity Rating", "Application"],
                   _refs(eu_ai_act=["Article 9"], iso_42001=["A.5.2", "A.5.3", "A.5.4", "A.5.5"], nist_ai_rmf=["GOVERN 1.3", "GOVERN 1.4", "GOVERN 4.2", "GOVERN 6.1", "MANAGE 1.2", "MANAGE 1.3", "MANAGE 1.4", "MAP 1.5", "MAP 5.1", "MEASURE 1.1", "MEASURE 2.10", "MEASURE 2.11", "MEASURE 3.1"], csa_aicm=["A&A-05", "A&A-06", "BCR-02", "CEK-07", "DSP-09", "GRC-02", "MDS-11", "MDS-12", "CCC-03"])),
            _ctrl("C002", "Conduct pre-deployment testing", "/safety/conduct-pre-deployment-testing", "Mandatory", "Preventative", "Every 12 months",
                   "Conduct internal testing of AI systems prior to deployment across risk categories.",
                   ["Universal"],
                   [_act("C002.1", "Conducting pre-deployment testing with documented results, risk assessments, and approval sign-offs.", "Core", ["Test results", "Risk assessments"]),
                    _act("C002.2", "Integrating AI system testing into established SDLC gates.", "Supplemental", ["CI/CD pipeline configuration"]),
                    _act("C002.3", "Implementing pre-deployment vulnerability scanning of AI artifacts and dependencies.", "Supplemental", ["Vulnerability scan results"])],
                   ["Internal Testing", "Pre-Deployment Testing"],
                   _refs(eu_ai_act=["Article 9", "Article 27"], iso_42001=["A.6.2.4", "A.6.2.5"], nist_ai_rmf=["GOVERN 4.3", "MANAGE 1.1", "MAP 4.2", "MEASURE 2.1", "MEASURE 2.3", "MEASURE 2.5", "MEASURE 4.3"], csa_aicm=["AIS-04", "AIS-05", "AIS-06", "AIS-07", "AIS-12", "CCC-02", "TVM-05"], mitre_atlas=["AML-M0016"])),
            _ctrl("C003", "Prevent harmful outputs", "/safety/prevent-harmful-outputs", "Mandatory", "Preventative", "Every 12 months",
                   "Implement safeguards to prevent harmful outputs including distressed outputs, angry responses, high-risk advice, offensive content, bias, and deception.",
                   ["Text-generation", "Voice-generation", "Image-generation"],
                   [_act("C003.1", "Detecting and blocking harmful output types through content filtering systems.", "Core", ["Content filtering rules"]),
                    _act("C003.2", "Restricting high-risk recommendations in sensitive domains with disclaimers.", "Core", ["System prompts", "Guardrail rules"]),
                    _act("C003.3", "Monitoring for discriminatory patterns and implementing fairness checks.", "Supplemental", ["Bias evaluation results"]),
                    _act("C003.4", "Evaluating harm mitigation controls using performance metrics.", "Supplemental", ["Performance metrics dashboard"])],
                   ["Harmful Outputs", "Distressed", "Angry", "Advice", "Offensive", "Bias"],
                   _refs(eu_ai_act=["Article 9"], nist_ai_rmf=["MEASURE 2.11"], owasp_llm_top10=["LLM05", "LLM09"], csa_aicm=["AIS-09", "GRC-11", "GRC-09", "LOG-15", "TVM-11"], owasp_aivss=["Agent Goal and Instruction Manipulation"])),
            _ctrl("C004", "Prevent out-of-scope outputs", "/safety/prevent-out-of-scope-outputs", "Mandatory", "Preventative", "Every 12 months",
                   "Implement safeguards to prevent out-of-scope outputs.",
                   ["Text-generation", "Voice-generation"],
                   [_act("C004.1", "Blocking rules, defensive prompting, or filtering for out-of-scope requests.", "Core", ["Technical configuration"]),
                    _act("C004.2", "Logs showing out-of-scope attempts with frequency data and boundary updates.", "Core", ["Log output"]),
                    _act("C004.3", "User-facing guidance explaining system capabilities and limitations.", "Supplemental", ["UI screenshots"])],
                   ["Out-of-Scope", "Political Discussion", "Technical Controls"],
                   _refs(eu_ai_act=["Article 72"], nist_ai_rmf=["MAP 2.2", "MAP 3.4"], owasp_llm_top10=["LLM05"], csa_aicm=["AIS-09", "GRC-09", "LOG-15", "TVM-11"], owasp_aivss=["Agent Goal and Instruction Manipulation"])),
            _ctrl("C005", "Prevent customer-defined high risk outputs", "/safety/prevent-other-high-risk-outputs", "Mandatory", "Preventative", "Every 12 months",
                   "Implement safeguards to prevent additional high risk outputs as defined in risk taxonomy.",
                   ["Universal"],
                   [_act("C005.1", "Implementing detection and blocking mechanisms aligned with organizational risk taxonomy.", "Core", ["Filtering rules"]),
                    _act("C005.2", "Establishing escalation procedures for flagged high-risk content.", "Supplemental", ["Workflow configuration"]),
                    _act("C005.3", "Implementing automated real-time interventions.", "Supplemental", ["Automated response configuration"])],
                   ["High-Risk Outputs", "Risk Taxonomy", "Technical Controls"],
                   _refs(eu_ai_act=["Article 9"], nist_ai_rmf=["MANAGE 1.4"], owasp_llm_top10=["LLM05"], csa_aicm=["GRC-09", "LOG-15", "TVM-11", "STA-10"], owasp_aivss=["Agent Goal and Instruction Manipulation"])),
            _ctrl("C006", "Prevent output vulnerabilities", "/safety/prevent-output-vulnerabilities", "Mandatory", "Preventative", "Every 3 months",
                   "Implement safeguards to prevent security vulnerabilities in outputs from impacting users.",
                   ["Universal"],
                   [_act("C006.1", "Establishing output sanitization and validation procedures before presenting content to users.", "Core", ["Output sanitization code"]),
                    _act("C006.2", "Implementing security labeling and content handling based on trust level.", "Core", ["Trust-based content handling"]),
                    _act("C006.3", "Detecting advanced output-based attack patterns.", "Supplemental", ["Detection rules"])],
                   ["Harmful Outputs", "Code Injection", "Data Exfiltration", "Application"],
                   _refs(eu_ai_act=["Article 72"], owasp_llm_top10=["LLM05"], csa_aicm=["AIS-09", "TVM-02", "AIS-07"], owasp_aivss=["Insecure Agent Critical Systems Interaction"], mitre_atlas=["AML-M0020"])),
            _ctrl("C007", "Flag high risk outputs", "/safety/flag-high-risk-recommendations", "Optional", "Preventative", "Every 12 months",
                   "Implement an alerting system that flags high-risk outputs for human review.",
                   ["Universal"],
                   [_act("C007.1", "Document or policy defining high-risk outputs requiring human review.", "Core", ["Legal Policies"]),
                    _act("C007.2", "Detection code, configuration, or rules engine showing high-risk output filtering.", "Core", ["Technical Implementation"]),
                    _act("C007.3", "Workflow documentation for human review process for flagged outputs.", "Supplemental", ["Operational Practices"])],
                   ["Human Review", "Escalation"],
                   _refs(iso_42001=["A.6.1.2", "A.9.3", "A.9.2"], nist_ai_rmf=["GOVERN 3.2", "MAP 3.5"], csa_aicm=["GRC-15"], owasp_aivss=["Agent Untraceability"], mitre_atlas=["AML-M0020"])),
            _ctrl("C008", "Monitor AI risk categories", "/safety/monitor-ai-risk-categories", "Optional", "Detective", "Every 12 months",
                   "Implement monitoring of AI systems across risk categories.",
                   ["Universal"],
                   [_act("C008.1", "Establish ongoing monitoring of AI outputs across risk categories through regular evaluations.", "Core", ["Monitoring dashboard"]),
                    _act("C008.2", "Maintain documentation recording identified risk scenarios with examples.", "Supplemental", ["Document/change log"]),
                    _act("C008.4", "Integrate AI output monitoring with existing security tools.", "Supplemental", ["SIEM integration"])],
                   ["Monitoring", "High-Risk Outputs"],
                   _refs(eu_ai_act=["Article 72"], iso_42001=["A.5.4", "A.6.2.6", "A.9.4"], nist_ai_rmf=["GOVERN 1.5", "MANAGE 3.1", "MANAGE 4.1", "MEASURE 2.4", "MEASURE 4.3"], csa_aicm=["GRC-02", "MDS-11", "TVM-03", "MDS-12", "TVM-07"], owasp_aivss=["Agent Untraceability"])),
            _ctrl("C009", "Enable real-time feedback and intervention", "/safety/collect-real-time-feedback", "Optional", "Preventative", "Every 3 months",
                   "Implement mechanisms to enable real-time user feedback collection and intervention mechanisms.",
                   ["Universal"],
                   [_act("C009.1", "Enable user intervention capabilities such as pause, stop, or redirect system behavior.", "Core", ["Intervention controls screenshots"]),
                    _act("C009.2", "Review user feedback and intervention logs regularly.", "Supplemental", ["Feedback review reports"])],
                   ["Feedback", "Intervention", "User Control", "Transparency"],
                   _refs(eu_ai_act=["Article 14"], iso_42001=["A.8.3"], nist_ai_rmf=["GOVERN 3.2", "MAP 3.5", "MEASURE 3.3"], csa_aicm=["GRC-15"])),
            _ctrl("C010", "Third-party testing for harmful outputs", "/safety/3rd-party-testing-for-harmful-outputs", "Mandatory", "Preventative", "Every 3 months",
                   "Appoint expert third parties to evaluate system robustness to harmful outputs at least every 3 months.",
                   ["Text-generation", "Voice-generation", "Image-generation"],
                   [_act("C010.1", "Third-party evaluation report showing harmful output testing.", "Core", ["Third-party evaluation report"])],
                   ["Harmful Outputs", "Third-Party Testing"],
                   _refs(eu_ai_act=["Article 9"], iso_42001=["A.6.2.4"], nist_ai_rmf=["GOVERN 4.3", "MANAGE 2.2", "MEASURE 1.3", "MEASURE 2.1", "MEASURE 2.6", "MEASURE 2.11", "MEASURE 4.1", "MEASURE 4.2"], csa_aicm=["GRC-11", "A&A-02", "TVM-06"])),
            _ctrl("C011", "Third-party testing for out-of-scope outputs", "/safety/3rd-party-testing-for-out-of-scope-outputs", "Mandatory", "Preventative", "Every 3 months",
                   "Appoint expert third parties to evaluate system robustness to out-of-scope outputs at least every 3 months.",
                   ["Text-generation", "Voice-generation"],
                   [_act("C011.1", "Third-party evaluation report showing out-of-scope output testing.", "Core", ["Third-party evaluation report"])],
                   ["Out-of-Scope", "Third-Party Testing"],
                   _refs(iso_42001=["A.6.2.4"], nist_ai_rmf=["GOVERN 4.3", "MANAGE 2.2", "MAP 2.2", "MEASURE 1.3", "MEASURE 2.1", "MEASURE 2.6", "MEASURE 4.1", "MEASURE 4.2"])),
            _ctrl("C012", "Third-party testing for customer-defined risk", "/safety/3rd-party-testing-for-other-risk", "Mandatory", "Preventative", "Every 3 months",
                   "Appoint expert third-parties to evaluate system robustness to additional high-risk outputs as defined in risk taxonomy.",
                   ["Universal"],
                   [_act("C012.1", "Third-party evaluation report showing testing of customer-defined risk.", "Core", ["Third-party evaluation report"])],
                   ["High-Risk Outputs", "Risk Taxonomy", "Third-Party Testing"],
                   _refs(iso_42001=["A.6.2.4"], nist_ai_rmf=["GOVERN 4.3", "MANAGE 2.2", "MEASURE 1.3", "MEASURE 2.1", "MEASURE 2.6", "MEASURE 4.1", "MEASURE 4.2"], csa_aicm=["A&A-02", "TVM-06"], owasp_aivss=["Agent Cascading Failures"])),
        ],
    }


# ── Domain D: Reliability ────────────────────────────────────────────────────


def _domain_d() -> dict:
    return {
        "id": "D",
        "name": "Reliability",
        "url": "https://www.aiuc-1.com/reliability",
        "description": "Ensure AI system outputs are accurate, grounded, and tool calls are safe",
        "controls": [
            _ctrl("D001", "Prevent hallucinated outputs", "/reliability/prevent-hallucinated-outputs", "Mandatory", "Preventative", "Every 12 months",
                   "Implement safeguards or technical controls to prevent hallucinated outputs.",
                   ["Text-generation", "Voice-generation"],
                   [_act("D001.1", "Implementing factual accuracy controls via fact-checking mechanisms, flagging uncertain responses.", "Core", ["Groundedness validation screenshots"]),
                    _act("D001.2", "Requiring citations for factual claims, implementing source reliability checks.", "Core", ["UI citation screenshots"]),
                    _act("D001.3", "Maintaining uncertainty communication through confidence levels and disclaimers.", "Core", ["Confidence display screenshots"])],
                   ["Hallucinations", "Technical Controls"],
                   _refs(nist_ai_rmf=["MEASURE 2.5"], owasp_llm_top10=["LLM05", "LLM09"], csa_aicm=["AIS-09", "MDS-10", "MDS-11"])),
            _ctrl("D002", "Third-party testing for hallucinations", "/reliability/3rd-party-testing-for-hallucinations", "Mandatory", "Preventative", "Every 3 months",
                   "Appoint expert third-parties to evaluate hallucinated outputs at least every 3 months.",
                   ["Text-generation", "Voice-generation"],
                   [_act("D002.1", "Third-party evaluation report showing hallucination testing results.", "Core", ["Third-party evaluation report"])],
                   ["Hallucinations", "Third-Party Testing"],
                   _refs(iso_42001=["A.6.2.4"], nist_ai_rmf=["GOVERN 4.3", "MANAGE 2.2", "MEASURE 1.3", "MEASURE 2.1", "MEASURE 2.5", "MEASURE 4.1", "MEASURE 4.2"], owasp_llm_top10=["LLM09"], csa_aicm=["AIS-09", "AIS-05", "MDS-06", "MDS-07"])),
            _ctrl("D003", "Restrict unsafe tool calls", "/reliability/restrict-unsafe-tool-calls", "Mandatory", "Preventative", "Every 12 months",
                   "Implement safeguards or technical controls to prevent tool calls in AI systems from executing unauthorized actions, accessing restricted information, or making decisions beyond their intended scope.",
                   ["Universal"],
                   [_act("D003.1", "Function call validation and authorization, restricting tool access to approved functions, validating parameters before execution.", "Core", ["Function allowlists", "Parameter validation code"]),
                    _act("D003.2", "Enforcing rate limits and transaction caps for autonomous tool use.", "Core", ["Rate limit configuration"]),
                    _act("D003.3", "Execution monitoring and logging; tracking all tool calls, monitoring for unauthorized access attempts.", "Core", ["Logging configuration", "Audit logs"]),
                    _act("D003.4", "Requiring human approval for sensitive tool operations.", "Supplemental", ["Workflow screenshots"]),
                    _act("D003.5", "Reviewing patterns of AI tool usage; identifying anomalies, updating tool permissions.", "Supplemental", ["Usage review reports"])],
                   ["Tool Calls", "Tool Selection", "Technical Controls"],
                   _refs(eu_ai_act=["Article 72"], nist_ai_rmf=["GOVERN 6.1"], owasp_llm_top10=["LLM06", "LLM08", "LLM10"], csa_aicm=["AIS-10", "AIS-06", "AIS-13", "AIS-11", "MDS-10", "MDS-11", "TVM-11", "TVM-12"], owasp_aivss=["Agentic AI Tool Misuse"], mitre_atlas=["AML-M0004", "AML-M0024"])),
            _ctrl("D004", "Third-party testing of tool calls", "/reliability/3rd-party-testing-of-tool-calls", "Mandatory", "Preventative", "Every 3 months",
                   "Appoint expert third-parties to evaluate tool calls in AI systems at least every 3 months.",
                   ["Universal"],
                   [_act("D004.1", "Third-party evaluation report showing tool call testing results.", "Core", ["Third-party evaluation report"])],
                   ["Tool Calls", "Tool Selection", "Third-Party Testing"],
                   _refs(iso_42001=["A.6.2.4"], nist_ai_rmf=["GOVERN 6.1", "GOVERN 4.3", "MANAGE 2.2", "MEASURE 1.3", "MEASURE 2.1", "MEASURE 2.6", "MEASURE 4.1", "MEASURE 4.2"], owasp_llm_top10=["LLM06"], csa_aicm=["AIS-05"], owasp_aivss=["Agentic AI Tool Misuse"])),
        ],
    }


# ── Domain E: Accountability ─────────────────────────────────────────────────


def _domain_e() -> dict:
    return {
        "id": "E",
        "name": "Accountability",
        "url": "https://www.aiuc-1.com/accountability",
        "description": "Ensure AI systems have clear ownership, oversight, and governance processes",
        "controls": [
            _ctrl("E001", "AI failure plan for security breaches", "/accountability/ai-failure-plan-for-security-breaches", "Mandatory", "Preventative", "Every 12 months",
                   "Document an AI failure plan addressing privacy and security breaches by assigning accountable owners and establishing notification and remediation procedures.",
                   ["Universal"],
                   [_act("E001.1", "Assign breach response lead and document incident response procedures.", "Core", ["AI failure plan"]),
                    _act("E001.2", "Define procedures for customer communications, regulatory reporting, and vendor notifications.", "Core", ["AI failure plan"]),
                    _act("E001.3", "Implement system freeze capabilities, vulnerability fixes, access control updates.", "Core", ["AI failure plan"]),
                    _act("E001.4", "Establish guidance on preserving evidence for legal review.", "Core", ["AI failure plan"])],
                   ["Incident Response", "Security", "Privacy"],
                   _refs(eu_ai_act=["Article 20", "Article 73"], iso_42001=["A.8.4", "A.8.5"], nist_ai_rmf=["GOVERN 4.3", "MANAGE 1.3", "MANAGE 4.3"], csa_aicm=["BCR-09", "BCR-10", "SEF-01", "SEF-02", "SEF-03", "SEF-04", "SEF-05", "SEF-07", "SEF-08", "SEF-09"])),
            _ctrl("E002", "AI failure plan for harmful outputs", "/accountability/ai-failure-plan-for-harmful-outputs", "Mandatory", "Preventative", "Every 12 months",
                   "Document AI failure plan for harmful AI outputs that cause significant customer harm.",
                   ["Text-generation", "Voice-generation", "Image-generation"],
                   [_act("E002.1", "Implementing customer communication protocols and immediate mitigation steps.", "Core", ["AI failure plan"]),
                    _act("E002.2", "Defining harmful output category definitions and external support engagement.", "Supplemental", ["AI failure plan"])],
                   ["Incident Response", "Emergency Response", "Harmful Outputs"],
                   _refs(eu_ai_act=["Article 20", "Article 73"], iso_42001=["A.8.4"], nist_ai_rmf=["GOVERN 4.3", "MANAGE 1.3", "MANAGE 4.3"], csa_aicm=["BCR-09", "BCR-10", "SEF-09"])),
            _ctrl("E003", "AI failure plan for hallucinations", "/accountability/ai-failure-plan-for-hallucinations", "Mandatory", "Preventative", "Every 12 months",
                   "Document AI failure plan for hallucinated AI outputs that cause substantial customer financial loss.",
                   ["Text-generation", "Voice-generation"],
                   [_act("E003.1", "Establishing compensation assessment procedures and remediation measures.", "Core", ["AI failure plan"]),
                    _act("E003.2", "Defining hallucination incident types and external support coordination.", "Supplemental", ["AI failure plan"])],
                   ["Hallucinations", "Incident Response", "Customer Loss"],
                   _refs(eu_ai_act=["Article 20", "Article 73"], iso_42001=["A.8.4"], nist_ai_rmf=["GOVERN 4.3", "MANAGE 1.3", "MANAGE 4.3"], csa_aicm=["BCR-09", "BCR-10", "SEF-09"])),
            _ctrl("E004", "Assign accountability", "/accountability/assign-accountability", "Mandatory", "Preventative", "Every 12 months",
                   "Document which AI system changes require formal review or approval, assign a lead accountable for each, and document their approval.",
                   ["Universal"],
                   [_act("E004.1", "Documentation defining which AI system changes require approval with assigned leads, plus approval records.", "Core", ["Change management policies"]),
                    _act("E004.2", "Implementing code signing and verification processes for AI models and deployment artifacts.", "Supplemental", ["Code signing configuration"])],
                   ["Decision Owners", "Deployment"],
                   _refs(eu_ai_act=["Article 17", "Article 18"], iso_42001=["A.3.2", "A.4.6", "A.6.2.2", "A.10.2"], nist_ai_rmf=["GOVERN 2.1", "GOVERN 2.3", "MAP 3.5", "MEASURE 2.8"], csa_aicm=["AIS-01", "AIS-04", "CCC-05", "CCC-03", "GRC-06", "CCC-01", "MDS-09"], mitre_atlas=["AML-M0013"])),
            _ctrl("E005", "Assess cloud vs on-prem processing", "/accountability/assess-cloud-vs-on-prem-processing", "Mandatory", "Preventative", "Every 12 months",
                   "Establish criteria for selecting cloud provider and circumstances for on-premises processing.",
                   ["Universal"],
                   [_act("E005.1", "Risk assessment and decision record evaluating cloud vs. on-premises factors.", "Core", ["Deployment decision memos"])],
                   ["Deployment", "Cloud Security", "Data Residency"],
                   _refs(nist_ai_rmf=["MAP 4.2"], owasp_llm_top10=["LLM03"], csa_aicm=["AIS-05"], owasp_aivss=["Agent Supply Chain and Dependency Risk"], mitre_atlas=["AML-M0017"])),
            _ctrl("E006", "Conduct vendor due diligence", "/accountability/conduct-vendor-due-diligence", "Mandatory", "Preventative", "Every 12 months",
                   "Establish AI vendor due diligence processes for foundation and upstream model providers.",
                   ["Universal"],
                   [_act("E006.1", "Vendor assessment records showing evaluation criteria, scoring, verification, and approval decisions.", "Core", ["Vendor assessment documentation"])],
                   ["Vendor Due Diligence", "Foundation Models"],
                   _refs(eu_ai_act=["Article 23", "Article 24"], iso_42001=["A.10.3"], nist_ai_rmf=["MAP 4.2"], owasp_llm_top10=["LLM03"], csa_aicm=["STA-01"], owasp_aivss=["Agent Supply Chain and Dependency Risk"])),
            _ctrl("E007", "Document system change approvals", "/accountability/document-system-change-approvals", "Optional", "Detective", "Every 12 months",
                   "RETIRED - Merged with E004 at Q1 2026 update.",
                   ["Universal"],
                   [_act("E007.1", "RETIRED - merged into E004.", "Core")],
                   ["Approvals", "Workflows"],
                   _refs(eu_ai_act=["Article 17", "Article 18"], iso_42001=["A.6.2.2", "A.6.2.4"], nist_ai_rmf=["GOVERN 2.1", "GOVERN 2.3", "MANAGE 1.1", "MAP 3.5", "MEASURE 2.8", "MEASURE 4.3"], csa_aicm=["CCC-01", "CCC-03", "CCC-04", "CCC-05", "CCC-06", "AIS-01"])),
            _ctrl("E008", "Review internal processes", "/accountability/review-internal-processes", "Mandatory", "Preventative", "Every 12 months",
                   "Establish regular internal reviews of key processes and document review records and approvals.",
                   ["Universal"],
                   [_act("E008.1", "Quarterly reviews of decision processes including AI system changes, foundational model selection.", "Core", ["Meeting notes", "Decision logs"]),
                    _act("E008.2", "Collect and implement external feedback on AI systems.", "Supplemental", ["Security advisories", "External input records"])],
                   ["Internal Reviews", "Documentation"],
                   _refs(eu_ai_act=["Article 43"], iso_42001=["A.3.3", "A.2.3", "A.2.4"], nist_ai_rmf=["GOVERN 1.7", "GOVERN 5.2", "GOVERN 5.1", "MANAGE 4.2", "MEASURE 1.2", "MEASURE 2.13"], csa_aicm=["A&A-02", "A&A-03", "A&A-05", "A&A-06", "BCR-01", "DSP-09", "GRC-03"])),
            _ctrl("E009", "Monitor third-party access", "/accountability/monitor-3rd-party-access", "Mandatory", "Preventative", "Every 12 months",
                   "Implement systems to monitor third-party access to AI systems.",
                   ["Universal"],
                   [_act("E009.1", "Configuring logging for third-party interactions with captured metadata.", "Core", ["Logging system screenshots"])],
                   ["Access", "Logins"],
                   _refs(eu_ai_act=["Article 72"], nist_ai_rmf=["GOVERN 1.5", "MANAGE 4.1"], owasp_llm_top10=["LLM03", "LLM05", "LLM06", "LLM10"], csa_aicm=["AIS-10", "LOG-05", "UEM-14", "TVM-05"], owasp_aivss=["Agent Supply Chain and Dependency Risk"], mitre_atlas=["AML-M0024"])),
            _ctrl("E010", "Establish AI acceptable use policy", "/accountability/establish-ai-acceptable-use-policy", "Mandatory", "Preventative", "Every 12 months",
                   "Establish and implement an AI acceptable use policy defining prohibited AI usage for end-users.",
                   ["Universal"],
                   [_act("E010.1", "Policy document defining acceptable and prohibited AI usage.", "Core", ["Acceptable Use Policy"]),
                    _act("E010.2", "Implementation of detection and monitoring systems for AUP violations.", "Core", ["Detection system code"]),
                    _act("E010.3", "User-facing alerts when acceptable use policy is violated.", "Core", ["UI screenshots"]),
                    _act("E010.4", "Real-time blocking/alerting capabilities and violation tracking.", "Supplemental", ["Enforcement configuration"])],
                   ["Acceptable Use", "Breach"],
                   _refs(iso_42001=["A.2.2", "A.9.2", "A.9.4", "A.2.4", "A.9.3"], nist_ai_rmf=["GOVERN 1.2", "MAP 1.6", "MAP 3.3", "MAP 3.4", "MEASURE 2.4"], owasp_llm_top10=["LLM10"], csa_aicm=["GRC-09"], owasp_aivss=["Agent Orchestration and Multi-Agent Exploitation"])),
            _ctrl("E011", "Record processing locations", "/accountability/record-processing-locations", "Mandatory", "Preventative", "Every 12 months",
                   "Document AI data processing locations covering geographic locations of processing and inference endpoints.",
                   ["Universal"],
                   [_act("E011.1", "Maintaining AI infrastructure location documentation.", "Core", ["Subprocessor list"]),
                    _act("E011.2", "Implementing transfer compliance procedures.", "Supplemental", ["DPA", "Transfer impact assessments"])],
                   ["Data Processing", "Storage Location"],
                   _refs(eu_ai_act=["Article 11"], iso_42001=["A.7.5"], nist_ai_rmf=["GOVERN 1.6"], csa_aicm=["DSP-13", "DSP-19", "UEM-04"])),
            _ctrl("E012", "Document regulatory compliance", "/accountability/document-regulatory-compliance", "Mandatory", "Preventative", "Every 6 months",
                   "Document applicable AI laws and standards, required data protections, and strategies for compliance.",
                   ["Universal"],
                   [_act("E012.1", "Identify applicable regulations, document compliance procedures, and review every 6 months.", "Core", ["Compliance register"])],
                   ["Regulatory", "EU", "GDPR", "NIST", "ISO"],
                   _refs(eu_ai_act=["Article 16", "Article 18", "Article 21", "Article 25", "Article 26", "Article 43", "Article 47", "Article 48", "Article 49"], iso_42001=["A.2.3", "A.8.5"], nist_ai_rmf=["GOVERN 1.1", "GOVERN 1.7", "MAP 1.1", "MAP 4.1"], csa_aicm=["A&A-04", "DSP-10", "DSP-18", "GRC-07", "HRS-10"])),
            _ctrl("E013", "Implement quality management system", "/accountability/implement-quality-management-system", "Optional", "Preventative", "Every 12 months",
                   "Establish a quality management system for AI systems proportionate to the size of the organization.",
                   ["Universal"],
                   [_act("E013.1", "Defining quality objectives, metrics, and risk management approach.", "Core", ["Quality metrics dashboards"]),
                    _act("E013.2", "Establishing change management, approval processes.", "Core", ["Change approval workflows"]),
                    _act("E013.3", "Implementing defect tracking, continuous improvement, and post-market monitoring.", "Core", ["Issue trackers"]),
                    _act("E013.4", "Establishing data management and record-keeping systems.", "Supplemental", ["Data governance policies"]),
                    _act("E013.5", "Documenting communication procedures with regulatory authorities.", "Supplemental", ["Incident reporting templates"])],
                   ["Quality management", "Regulatory"],
                   _refs(eu_ai_act=["Article 9", "Article 10", "Article 11", "Article 12", "Article 16", "Article 17", "Article 18", "Article 19", "Article 26", "Article 43", "Article 72", "Article 73"], iso_42001=["A.5.2", "A.6.2.7", "A.5.3", "A.5.4", "A.4.2"], nist_ai_rmf=["GOVERN 1.4", "GOVERN 1.3"], csa_aicm=["AIS-01", "AIS-03", "BCR-02", "DSP-09", "GRC-02", "GRC-10", "MDS-02", "A&A-05", "CCC-02", "TVM-01", "TVM-02", "SEF-01"], owasp_aivss=["Agent Supply Chain and Dependency Risk"])),
            _ctrl("E014", "Share transparency reports", "/accountability/share-transparency-reports", "Optional", "Preventative", "Every 12 months",
                   "RETIRED - Merged into E017 at Q1 2026 update.",
                   ["Universal"],
                   [_act("E014.1", "RETIRED - merged into E017.", "Core")],
                   ["Transparency"],
                   _refs(eu_ai_act=["Article 11"], iso_42001=["A.6.2.7", "A.8.2", "A.8.5"], nist_ai_rmf=["MANAGE 4.2", "MANAGE 4.3", "MAP 1.6", "MAP 5.2", "MEASURE 2.8", "MEASURE 2.9", "MEASURE 4.2"], csa_aicm=["GRC-14", "TVM-09", "TVM-10", "A&A-06", "LOG-13", "LOG-10", "SEF-05", "SEF-07"])),
            _ctrl("E015", "Log model activity", "/accountability/log-model-activity", "Mandatory", "Detective", "Every 12 months",
                   "Maintain logs of AI system processes, actions, and model outputs to support incident investigation, auditing, and explanation.",
                   ["Universal"],
                   [_act("E015.1", "Capture system activity details including inputs, processing steps, outputs, and metadata.", "Core", ["Logging system screenshots"]),
                    _act("E015.2", "Implement storage with retention policies, access controls, and data sanitation.", "Core", ["Log management platform"]),
                    _act("E015.3", "Ensure logs are tamper-evident and independently verifiable.", "Supplemental", ["WORM storage", "Cryptographic hashing"])],
                   ["Explainability", "Logs", "Audit Trail"],
                   _refs(eu_ai_act=["Article 12", "Article 19"], iso_42001=["A.6.2.8"], nist_ai_rmf=["MEASURE 2.4", "MEASURE 2.8"], owasp_llm_top10=["LLM10"], csa_aicm=["LOG-01", "MDS-10", "SEF-05", "SEF-07"], owasp_aivss=["Agent Untraceability"], mitre_atlas=["AML-M0024"])),
            _ctrl("E016", "Implement AI disclosure mechanisms", "/accountability/implement-ai-disclosure-mechanisms", "Mandatory", "Preventative", "Every 12 months",
                   "Implement clear disclosure mechanisms to inform users when they are interacting with AI systems.",
                   ["Universal"],
                   [_act("E016.1", "Display clear notices when users interact with AI chatbots.", "Core", ["Text AI disclosure screenshots"]),
                    _act("E016.2", "Provide audio notifications at the beginning of voice calls.", "Core", ["Voice AI disclosure transcripts"]),
                    _act("E016.3", "Mark AI-generated content with metadata, watermarks, or labels.", "Core", ["Content labeling screenshots"]),
                    _act("E016.4", "Notify users when autonomous AI agents perform actions.", "Core", ["Automation disclosure screenshots"]),
                    _act("E016.5", "Systems respond to user questions about whether they are interacting with AI.", "Core", ["AI inquiry response screenshots"])],
                   ["Labelling", "Transparency"],
                   _refs(eu_ai_act=["Article 13", "Article 50"], iso_42001=["A.8.2"], nist_ai_rmf=["MAP 2.2", "MAP 3.4", "MEASURE 2.8"], csa_aicm=["GRC-15"], owasp_aivss=["Agent Identity Impersonation"])),
            _ctrl("E017", "Document system transparency policy", "/accountability/document-system-transparency-policy", "Optional", "Preventative", "Every 12 months",
                   "Establish a system transparency policy and maintain a repository of model cards, datasheets, and interpretability reports.",
                   ["Universal"],
                   [_act("E017.1", "Policy document defining transparency documentation requirements.", "Core", ["Transparency policy"]),
                    _act("E017.2", "Transparency documentation artifacts: model cards, datasheets, interpretability reports, AI Bill of Materials.", "Core", ["Model cards", "AIBOM"]),
                    _act("E017.3", "Policy defining transparency sharing practices with stakeholder categories.", "Supplemental", ["Sharing policy"])],
                   ["Transparency", "System Cards"],
                   _refs(eu_ai_act=["Article 11"], iso_42001=["A.4.2", "A.4.3", "A.4.4", "A.4.5", "A.6.2.3", "A.2.2", "A.2.4"], nist_ai_rmf=["GOVERN 1.2", "GOVERN 1.6", "MAP 1.6", "MEASURE 2.8", "MEASURE 2.9", "MEASURE 4.3"], csa_aicm=["GRC-13", "GRC-14", "MDS-03", "MDS-04", "MDS-05", "STA-16", "DSP-20"], mitre_atlas=["AML-M0023", "AML-M0025"])),
        ],
    }


# ── Domain F: Society ────────────────────────────────────────────────────────


def _domain_f() -> dict:
    return {
        "id": "F",
        "name": "Society",
        "url": "https://www.aiuc-1.com/society",
        "description": "Prevent AI from enabling societal harm through cyberattacks or catastrophic misuse",
        "controls": [
            _ctrl("F001", "Prevent AI cyber misuse", "/society/prevent-ai-cyber-misuse", "Mandatory", "Preventative", "Every 12 months",
                   "Implement or document guardrails to prevent AI-enabled misuse for cyber attacks and exploitation.",
                   ["Text-generation", "Automation", "Voice-generation"],
                   [_act("F001.1", "Provider model cards and documentation describing offensive cyber capabilities and mitigation strategies.", "Core", ["Vendor documentation"]),
                    _act("F001.2", "Deploy content filtering to detect requests for malicious code generation and vulnerability exploitation.", "Supplemental", ["Content filtering rules"])],
                   ["Cyber Attacks"],
                   _refs(iso_42001=["A.5.5"], nist_ai_rmf=["MEASURE 2.7"], csa_aicm=["GRC-02", "GRC-09", "GRC-10", "GRC-12", "TVM-11"], owasp_aivss=["Agent Identity Impersonation"])),
            _ctrl("F002", "Prevent catastrophic misuse", "/society/prevent-catastrophic-misuse", "Mandatory", "Detective", "Every 12 months",
                   "Implement or document guardrails to prevent AI-enabled catastrophic system misuse (chemical / bio / radio / nuclear).",
                   ["Text-generation", "Voice-generation", "Image-generation"],
                   [_act("F002.1", "List of foundation models with CBRN capability information and risk evaluations.", "Core", ["Vendor documentation"]),
                    _act("F002.2", "Monitoring dashboard or alert configuration for catastrophic misuse patterns.", "Supplemental", ["Monitoring configuration"])],
                   ["CBRN", "Chemical", "Bioweapon", "Radioactive", "Nuclear"],
                   _refs(iso_42001=["A.5.5"], csa_aicm=["GRC-02", "GRC-09", "GRC-10", "GRC-12", "TVM-11"])),
        ],
    }


def main() -> None:
    data = build_aiuc_standard()
    output_path = Path(__file__).parent.parent / "aiuc" / "aiuc-1-standard.json"
    with open(output_path, "w") as f:
        json.dump(data, f, indent=2)

    # Count controls and activities
    total_controls = sum(len(d["controls"]) for d in data["domains"])
    total_activities = sum(
        len(c["activities"])
        for d in data["domains"]
        for c in d["controls"]
    )
    print(f"Written {output_path}")
    print(f"  Domains: {len(data['domains'])}")
    print(f"  Controls: {total_controls}")
    print(f"  Activities: {total_activities}")


if __name__ == "__main__":
    main()
